//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permanents
    {
        public int user_id { get; set; }
        public int permanent_id { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<int> free_entries { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
